### ISSUE TITLE
Render issue on iPhone and iPad safari

### ISSUE THREAD

**Issue by DDDOH** [atelier-anchor/atelier-anchor.github.io#2]
I tried viewing https://atelier-anchor.com/ with safari on both iPhone and iPad. iPhone is running iOS 15.5, iPad is running iOS 15.7. The page is not rendered properly. As shown in this screen recording.

https://user-images.githubusercontent.com/25512742/224104723-7cf7a13c-a1d7-4885-be60-f28bffb5b4ae.MP4

**Comment by stone-zeng** [comment]
It looks like the issue is just due to the unstable internet connection 🤦

**Comment by DDDOH** [comment]
I am not sure. I tested viewing this website with cellular signal and multiple wifi connections. The behavior is similar.

我用4G信号和好几个不同地方的Wi-Fi都测试了，表现和上面视频里相似。同样Wi-Fi下，MacBook上的Safari能够正确渲染。在iPhone上刚刷新的时候能看到一部分内容，一瞬间之后就看不到了。我怀疑是网页用了一些iOS15的Safari不支持的特效🤔或许iOS16的Safari能正常渲染？
